spring:
  config:
    activate:
      on-profile: local

  application:
    name: bows
  datasource:
    url: jdbc:mysql://localhost:3306/bows
    username: bows_dev
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

cors:
  originUrl: http://localhost:5173

kube:
  configPath: "/.kube/config"
  helm:
    repoName: "simpleApp"
    chartName: "bows-simpleApp"

security:
  invitationCode: "ASDF"
  jwtSecretKey: "dklfjalskjlkqjfmnfoqfnqowifnlkdaslkdjsanfalksfnasknlf"

file:
  multipart:
    max-upload-size: 100
    max-request-size: 100