spring:
  config:
    activate:
      on-profile: prod

  application:
    name: bows
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

cors:
  originUrl: http://bows.co.kr:81

kube:
  configPath: "/.kube/config"
  helm:
    repoName: "simpleApp"
    chartName: "bows-simpleApp"